version: "3.4"

services:
    telegram:
        container_name: telegram
        build:
            context: .
        volumes:
            - .:/usr/src/app
        ports:
            - 3520:3520
        restart: unless-stopped
        networks:
            - raspberry-swag

networks:
    raspberry-swag:
        name: swag-reverseproxy_raspberry-swag
        external: true
